apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deployment
  labels:
    app: lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
        - name: lb
          image: lb
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /go/src/app
              name: code
      volumes:
        - name: code
          hostPath:
            path: /code
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: ClusterIP
  selector:
    app: lb
  ports:
    - port: 8080
      targetPort: 8080
