apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deployment-rust
  labels:
    app: lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-rust
  template:
    metadata:
      labels:
        app: lb-rust
    spec:
      containers:
        - name: lb-rust
          image: lb-rust
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app
              name: code
      volumes:
        - name: code
          hostPath:
            path: /code
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service-rust
spec:
  type: ClusterIP
  selector:
    app: lb-rust
  ports:
    - port: 8080
      targetPort: 8080
